use_frameworks!

target 'SDWebImagePDFCoder_Example' do
  platform :ios, '9.3'
  pod 'SDWebImagePDFCoder', :path => '../'

  target 'SDWebImagePDFCoder_Tests' do
    inherit! :search_paths

    
  end
end

target 'SDWebImagePDFCoder_Example macOS' do
  platform :osx, '10.13'
  pod 'SDWebImagePDFCoder', :path => '../'
end